-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-04-24 00:53:11 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE auto_ins (
    cust_id              CHAR(10) NOT NULL COMMENT 'unique customer id',
    auto_ins_id          CHAR(10) NOT NULL COMMENT 'Unique identifier for insurance policy',
    auto_ins_start_date  DATETIME COMMENT 'Insurance start date',
    auto_ins_end_date    DATETIME NOT NULL COMMENT 'Insurance end date',
    auto_ins_prem_amt    DOUBLE NOT NULL COMMENT 'Insurance premium amount in USD xxxxx.xx',
    auto_ins_status      CHAR(1) NOT NULL COMMENT 'C is current, P is expired'
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins.cust_id IS
    'unique customer id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins.auto_ins_id IS
    'Unique identifier for insurance policy'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins.auto_ins_start_date IS
    'Insurance start date'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins.auto_ins_end_date IS
    'Insurance end date'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins.auto_ins_prem_amt IS
    'Insurance premium amount in USD xxxxx.xx'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins.auto_ins_status IS
    'C is current, P is expired'; */

ALTER TABLE auto_ins ADD CONSTRAINT auto_ins_pk PRIMARY KEY ( cust_id );

ALTER TABLE auto_ins ADD CONSTRAINT auto_ins_pkv1 UNIQUE ( auto_ins_id );

CREATE TABLE auto_ins_car (
    cust_id                   CHAR(10) NOT NULL COMMENT 'unique customer id',
    auto_ins_id               CHAR(9) COMMENT 'Unique identifier',
    auto_ins_vehicle_vin      CHAR(9) NOT NULL COMMENT 'Vehicle identification number',
    auto_ins_make_model_year  VARCHAR(4000) NOT NULL COMMENT 'Store the make, model, year',
    auto_ins_vehicle_status   CHAR(1) NOT NULL COMMENT ' “L”, “F”, or “O” representing “Leased”, Financed”, “and Owned’.',
    auto_ins_auto_ins_id      CHAR(10) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins_car.cust_id IS
    'unique customer id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins_car.auto_ins_id IS
    'Unique identifier'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins_car.auto_ins_vehicle_vin IS
    'Vehicle identification number'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins_car.auto_ins_make_model_year IS
    'Store the make, model, year'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins_car.auto_ins_vehicle_status IS
    ' “L”, “F”, or “O” representing “Leased”, Financed”, “and Owned’.'; */

ALTER TABLE auto_ins_car ADD CONSTRAINT auto_ins_car_pk PRIMARY KEY ( cust_id );

CREATE TABLE auto_ins_pay (
    cust_id                   CHAR(10) NOT NULL COMMENT 'unique customer id',
    auto_ins_pay_id           unknown 
--  ERROR: Datatype UNKNOWN is not allowed 
     NOT NULL COMMENT 'Unique payment id ',
    auto_ins_id               unknown 
--  ERROR: Datatype UNKNOWN is not allowed 
     NOT NULL COMMENT 'insurance payment id',
    auto_ins_pay_type         CHAR(6) NOT NULL COMMENT 'Payment type “PayPal”, “Credit”, “Debit”, “Check"',
    auto_ins_pay_amount       DOUBLE NOT NULL COMMENT 'Premium amount paid',
    auto_ins_installment_id   CHAR 
--  WARNING: CHAR size not specified 
     NOT NULL,
    auto_ins_installment_id1  CHAR 
--  WARNING: CHAR size not specified 
     NOT NULL,
    auto_ins_cust_id          CHAR(10) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins_pay.cust_id IS
    'unique customer id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins_pay.auto_ins_pay_id IS
    'Unique payment id '; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins_pay.auto_ins_id IS
    'insurance payment id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins_pay.auto_ins_pay_type IS
    'Payment type “PayPal”, “Credit”, “Debit”, “Check"'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_ins_pay.auto_ins_pay_amount IS
    'Premium amount paid'; */

ALTER TABLE auto_ins_pay ADD CONSTRAINT auto_ins_pay_pk PRIMARY KEY ( cust_id );

ALTER TABLE auto_ins_pay ADD CONSTRAINT auto_ins_pay_pkv1 UNIQUE ( auto_ins_pay_id );

CREATE TABLE auto_invoice (
    cust_id                   CHAR(10) NOT NULL COMMENT 'unique customer id',
    auto_ins_id               CHAR(9) COMMENT 'Insurance policy unique id',
    auto_ins_installment_id   CHAR(9) NOT NULL COMMENT 'Unique installment id',
    auto_ins_inst_date        DATETIME NOT NULL COMMENT 'Insurance installment date',
    auto_ins_inst_amt         DOUBLE NOT NULL COMMENT 'Auto insurance installment amount',
    auto_ins_installment_id1  CHAR 
--  WARNING: CHAR size not specified 
     NOT NULL,
    auto_ins_auto_ins_id      CHAR(10) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_invoice.cust_id IS
    'unique customer id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_invoice.auto_ins_id IS
    'Insurance policy unique id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_invoice.auto_ins_installment_id IS
    'Unique installment id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_invoice.auto_ins_inst_date IS
    'Insurance installment date'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN auto_invoice.auto_ins_inst_amt IS
    'Auto insurance installment amount'; */

ALTER TABLE auto_invoice ADD CONSTRAINT auto_invoice_pk PRIMARY KEY ( cust_id );

ALTER TABLE auto_invoice ADD CONSTRAINT auto_invoice_pkv1 UNIQUE ( auto_ins_installment_id );

CREATE TABLE cust_details (
    cust_id         CHAR(10) NOT NULL COMMENT 'unique customer id',
    gender          CHAR(1) COMMENT 'gender. M for male, F for female, blank for doest want to disclose',
    marital_status  CHAR(1) NOT NULL COMMENT ' “M”, “S”, or “W”, representing “Married”, “Single”, and “Widow/Widower”',
    address         VARCHAR(4000) COMMENT 'primary address of customer',
    cust_type       CHAR(1) COMMENT 'A, H, B for automotive, home or both type of insurance respectively '
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN cust_details.cust_id IS
    'unique customer id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN cust_details.gender IS
    'gender. M for male, F for female, blank for doest want to disclose'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN cust_details.marital_status IS
    ' “M”, “S”, or “W”, representing “Married”, “Single”, and “Widow/Widower”'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN cust_details.address IS
    'primary address of customer'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN cust_details.cust_type IS
    'A, H, B for automotive, home or both type of insurance respectively '; */

ALTER TABLE cust_details ADD CONSTRAINT cust_details_pk PRIMARY KEY ( cust_id );

CREATE TABLE driver (
    cust_id                CHAR(10) NOT NULL COMMENT 'unique customer id',
    auto_ins_vin           CHAR(9) NOT NULL,
    auto_driver_license    CHAR(10) NOT NULL COMMENT 'Driver license',
    auto_driver_name       CHAR(30) NOT NULL COMMENT 'Driver name',
    auto_driver_birthdate  DATETIME NOT NULL COMMENT 'birthdate of driver',
    auto_ins_vin1          CHAR 
--  WARNING: CHAR size not specified 
     NOT NULL,
    auto_driver_license1   CHAR 
--  WARNING: CHAR size not specified 
     NOT NULL,
    auto_ins_car_cust_id   CHAR(10) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN driver.cust_id IS
    'unique customer id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN driver.auto_driver_license IS
    'Driver license'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN driver.auto_driver_name IS
    'Driver name'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN driver.auto_driver_birthdate IS
    'birthdate of driver'; */

ALTER TABLE driver ADD CONSTRAINT driver_pk PRIMARY KEY ( cust_id );

ALTER TABLE driver ADD CONSTRAINT driver_pkv1 UNIQUE ( auto_ins_vin,
                                                       auto_driver_license );

CREATE TABLE home_details (
    cust_id                     CHAR(10) NOT NULL COMMENT 'unique customer id',
    home_unique_id              VARCHAR(10) NOT NULL COMMENT 'home identification code',
    home_purchase_date          DATETIME NOT NULL COMMENT 'home purchase date',
    home_purchase_value         DOUBLE NOT NULL COMMENT 'Money paid to buy the house in USD xxxxxxxxxxx.xx',
    home_area_sq_ft             DOUBLE NOT NULL COMMENT 'House area in square feet',
    home_type                   CHAR(1) NOT NULL COMMENT 'S,M,C,T representing Single family, Multi Family, Condominium, Town house respectively',
    home_auto_fire_notif        LONGBLOB NOT NULL COMMENT '0 - no fire notification to fire depart, 1 - automatic notification to fire department',
    home_security_system        LONGBLOB NOT NULL COMMENT '0 -  home security system is not installed or not monitored, 1 -  home security system is installed and monitored',
    home_swim_pool              CHAR(1) COMMENT 'U - underground pool, O - overground pool, M - multiple pool, blank - no pool',
    home_basement               LONGBLOB NOT NULL COMMENT '0 - no basement, 1 - basement',
    home_insurance_home_ins_id  CHAR(10) NOT NULL,
    home_id                     CHAR(9) NOT NULL COMMENT 'Unique id for every home',
    home_insurance_home_id      CHAR(9) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_details.cust_id IS
    'unique customer id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_details.home_unique_id IS
    'home identification code'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_details.home_purchase_date IS
    'home purchase date'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_details.home_purchase_value IS
    'Money paid to buy the house in USD xxxxxxxxxxx.xx'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_details.home_area_sq_ft IS
    'House area in square feet'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_details.home_type IS
    'S,M,C,T representing Single family, Multi Family, Condominium, Town house respectively'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_details.home_auto_fire_notif IS
    '0 - no fire notification to fire depart, 1 - automatic notification to fire department'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_details.home_security_system IS
    '0 -  home security system is not installed or not monitored, 1 -  home security system is installed and monitored'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_details.home_swim_pool IS
    'U - underground pool, O - overground pool, M - multiple pool, blank - no pool'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_details.home_basement IS
    '0 - no basement, 1 - basement'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_details.home_id IS
    'Unique id for every home'; */

ALTER TABLE home_details ADD CONSTRAINT home_details_pk PRIMARY KEY ( cust_id );

ALTER TABLE home_details
    ADD CONSTRAINT home_details_pkv1 UNIQUE ( home_insurance_home_ins_id,
                                              home_insurance_home_id,
                                              home_id );

CREATE TABLE home_insurance (
    cust_id               CHAR(10) NOT NULL COMMENT 'unique customer id',
    home_ins_id           CHAR(10) NOT NULL COMMENT 'Unique insurance policy identifier',
    home_ins_start_date   DATETIME NOT NULL COMMENT 'start date of insurance policy',
    home_ins_end_date     DATETIME NOT NULL COMMENT 'end date of insurance policy',
    home_ins_pre_amt      DOUBLE NOT NULL COMMENT 'insurance premium in USD xxxxxxxxxxx.xx',
    home_ins_status       CHAR(1) NOT NULL COMMENT 'C for current, P for expired',
    home_ins_homes        VARCHAR(1000) NOT NULL COMMENT 'Holds unique home id, we would have to seperate it with a ","',
    home_ins_invoice_ids  VARCHAR(1000) NOT NULL COMMENT 'holds the invoice ids',
    home_ins_payment      VARCHAR(1000) NOT NULL COMMENT 'payment details saved as a string, seperated by a comma ","',
    home_id               CHAR(9) NOT NULL COMMENT 'Unique id for every home',
    home_ins_id1          CHAR 
--  WARNING: CHAR size not specified 
     NOT NULL,
    home_invoice_id       CHAR(9) NOT NULL COMMENT 'unique invoice id'
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_insurance.cust_id IS
    'unique customer id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_insurance.home_ins_id IS
    'Unique insurance policy identifier'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_insurance.home_ins_start_date IS
    'start date of insurance policy'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_insurance.home_ins_end_date IS
    'end date of insurance policy'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_insurance.home_ins_pre_amt IS
    'insurance premium in USD xxxxxxxxxxx.xx'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_insurance.home_ins_status IS
    'C for current, P for expired'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_insurance.home_ins_homes IS
    'Holds unique home id, we would have to seperate it with a ","'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_insurance.home_ins_invoice_ids IS
    'holds the invoice ids'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_insurance.home_ins_payment IS
    'payment details saved as a string, seperated by a comma ","'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_insurance.home_id IS
    'Unique id for every home'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN home_insurance.home_invoice_id IS
    'unique invoice id'; */

ALTER TABLE home_insurance ADD CONSTRAINT home_insurance_pk PRIMARY KEY ( cust_id );

ALTER TABLE home_insurance ADD CONSTRAINT home_insurance_pkv1 UNIQUE ( home_ins_id,
                                                                       home_id );

CREATE TABLE invoice (
    cust_id                     CHAR(10) NOT NULL COMMENT 'unique customer id',
    invoice_id                  CHAR(9) COMMENT 'Unique invoice details',
    invoice_due_date            DATETIME COMMENT 'Last date for invoice',
    invoice_amount              DOUBLE NOT NULL COMMENT 'Invoice due amount in USD xxxxxxx.xx',
    home_insurance_home_ins_id  CHAR(10) NOT NULL,
    home_insurance_home_id      CHAR(9) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN invoice.cust_id IS
    'unique customer id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN invoice.invoice_id IS
    'Unique invoice details'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN invoice.invoice_due_date IS
    'Last date for invoice'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN invoice.invoice_amount IS
    'Invoice due amount in USD xxxxxxx.xx'; */

ALTER TABLE invoice ADD CONSTRAINT invoice_pk PRIMARY KEY ( cust_id );

ALTER TABLE invoice ADD CONSTRAINT invoice_pkv1 UNIQUE ( home_insurance_home_ins_id,
                                                         home_insurance_home_id );

CREATE TABLE payment (
    cust_id                     CHAR(10) NOT NULL COMMENT 'unique customer id',
    payment_id                  CHAR(9) NOT NULL COMMENT 'unique payment identifier',
    payment_date                DATETIME NOT NULL COMMENT 'payment date',
    payment_type                VARCHAR(6) NOT NULL COMMENT 'Options include “PayPal”, “Credit”, “Debit”, “Check"',
    home_insurance_home_ins_id  CHAR(10) NOT NULL,
    home_insurance_home_id      CHAR(9) NOT NULL
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN payment.cust_id IS
    'unique customer id'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN payment.payment_id IS
    'unique payment identifier'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN payment.payment_date IS
    'payment date'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN payment.payment_type IS
    'Options include “PayPal”, “Credit”, “Debit”, “Check"'; */

ALTER TABLE payment ADD CONSTRAINT payment_pk PRIMARY KEY ( cust_id );

ALTER TABLE payment
    ADD CONSTRAINT payment_pkv1 UNIQUE ( payment_id,
                                         home_insurance_home_ins_id,
                                         home_insurance_home_id );

ALTER TABLE auto_ins_car
    ADD CONSTRAINT auto_ins_car_auto_ins_fk FOREIGN KEY ( auto_ins_auto_ins_id )
        REFERENCES auto_ins ( auto_ins_id );

ALTER TABLE auto_ins_car
    ADD CONSTRAINT auto_ins_car_cust_details_fk FOREIGN KEY ( cust_id )
        REFERENCES cust_details ( cust_id );

ALTER TABLE auto_ins
    ADD CONSTRAINT auto_ins_cust_details_fk FOREIGN KEY ( cust_id )
        REFERENCES cust_details ( cust_id );

ALTER TABLE auto_ins_pay
    ADD CONSTRAINT auto_ins_pay_auto_ins_fk FOREIGN KEY ( auto_ins_cust_id )
        REFERENCES auto_ins ( cust_id );

ALTER TABLE auto_ins_pay
    ADD CONSTRAINT auto_ins_pay_cust_details_fk FOREIGN KEY ( cust_id )
        REFERENCES cust_details ( cust_id );

ALTER TABLE auto_invoice
    ADD CONSTRAINT auto_invoice_auto_ins_fk FOREIGN KEY ( auto_ins_auto_ins_id )
        REFERENCES auto_ins ( auto_ins_id );

ALTER TABLE auto_invoice
    ADD CONSTRAINT auto_invoice_cust_details_fk FOREIGN KEY ( cust_id )
        REFERENCES cust_details ( cust_id );

ALTER TABLE driver
    ADD CONSTRAINT driver_auto_ins_car_fk FOREIGN KEY ( auto_ins_car_cust_id )
        REFERENCES auto_ins_car ( cust_id );

ALTER TABLE driver
    ADD CONSTRAINT driver_cust_details_fk FOREIGN KEY ( cust_id )
        REFERENCES cust_details ( cust_id );

ALTER TABLE home_details
    ADD CONSTRAINT home_details_cust_details_fk FOREIGN KEY ( cust_id )
        REFERENCES cust_details ( cust_id );

ALTER TABLE home_details
    ADD CONSTRAINT home_details_home_insurance_fk FOREIGN KEY ( home_insurance_home_ins_id,
                                                                home_insurance_home_id )
        REFERENCES home_insurance ( home_ins_id,
                                    home_id );

ALTER TABLE home_insurance
    ADD CONSTRAINT home_insurance_cust_details_fk FOREIGN KEY ( cust_id )
        REFERENCES cust_details ( cust_id );

ALTER TABLE invoice
    ADD CONSTRAINT invoice_cust_details_fk FOREIGN KEY ( cust_id )
        REFERENCES cust_details ( cust_id );

ALTER TABLE invoice
    ADD CONSTRAINT invoice_home_insurance_fk FOREIGN KEY ( home_insurance_home_ins_id,
                                                           home_insurance_home_id )
        REFERENCES home_insurance ( home_ins_id,
                                    home_id );

ALTER TABLE payment
    ADD CONSTRAINT payment_cust_details_fk FOREIGN KEY ( cust_id )
        REFERENCES cust_details ( cust_id );

ALTER TABLE payment
    ADD CONSTRAINT payment_home_insurance_fk FOREIGN KEY ( home_insurance_home_ins_id,
                                                           home_insurance_home_id )
        REFERENCES home_insurance ( home_ins_id,
                                    home_id );

